mysql:
  host: localhost
  port: 3306
  username: root
  password: root
  database: skillfull_logging_service


redis:
  host: localhost
  port: 6379
  password: root
  database: 15


rbmq:
  host: localhost
  port: 5672
  username: guest
  password: guest


app:
  server-port: 8085
  context-path: /logging
  log-root-level: info
  delete-log-type: 1 # 日志删除方式：0-物理删除,1-逻辑删除,默认1
  log-package-level: debug
  enable-gray: true # 是否启用灰度
  enable-doc: true # 是否打开swagger
  create-out-conf: false  # 启动是否创建外置配置文件
